development:
  adapter: postgresql
  encoding: unicode
  database: sample_app_development
  pool: 5
  username: Jeremy
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: sample_app_test
  pool: 5
  username: Jeremy
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: sample_app_production
  pool: 5
  username: Jeremy
  password:
